name: Xcode - Build and Analyze

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby Bundler
        run: gem install bundler:2.3.11
      - name: Install Ruby Gems
        run: bundle install
      - name: Install Arkana
        run: bundle exec arkana -e ./env/.env
      - name: Install Pods
        run: bundle exec pod install
      - name: Build project
        run: |
          set -eo pipefail
          time xcodebuild clean build -workspace Mastodon.xcworkspace \
          -scheme Mastodon \
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
